name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deployment_pipeline:
    needs: [test]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    if: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip') }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notify_discord:
    if: always()
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Send warning about skipped deployment to discord webhook
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ contains(join(github.event.commits.*.message, ', '), '#skip') }}
        with:
          severity: warning
          details: Production deployment was skipped because a commit message included \#skip 🤔
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send success message to discord webhook
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ needs.deployment_pipeline.result == 'success' }}
        with:
          severity: info
          details: A new version of bloglist deployed! 🚀 https://fullstack-osa11-bloglist.fly.dev/
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send failure message to discord webhook
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ needs.simple_deployment_pipeline.result != 'success' }}
        with:
          severity: error
          details: Deployment pipeline failed! 😢
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
