name: Lint and test code

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  run_eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: npm ci
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Lint code
        run: npm run lint
  unit_test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests for backend
        run: npm test
  unit_test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run unit tests for frontend
        run: npm test
        working-directory: ./frontend
  run_e2e_cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install backend dependencies
        run: npm ci
      - name: Run backend server
        run: npm run dev:test &
        env:
          SECRET: ${{ secrets.JWT_SECRET }}
          TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
          PORT: 3003
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Run frontend server
        run: npm run dev &
        working-directory: ./frontend
      - name: Run e2e tests with Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          command: npm run test:e2e
          wait-on: http://localhost:5173
